#!/bin/bash

case $1 in
  config)
    cat <<'EOM'
graph_title Storage space
graph_args --base 1024 -l 0
graph_category storage
graph_vlabel space
used.label used
free.label free
EOM
    exit 0;;
esac

df_line=$(df | grep 'hubicfuse')

free_space=$(echo $df_line | awk '{print $4}')
used_space=$(echo $df_line | awk '{print $3}')

printf "used.value $used_space\n"
printf "free.value $free_space\n"
